#!/usr/bin/env python3
"""第三批全国重点文物保护单位数据导入 (258项)"""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from batch1_import import PROVINCE_CODE, PROVINCE_FULL

BATCH3 = [
    # === 近现代重要史迹及代表性建筑 (1-41) ===
    {"seq": 1, "id_num": "3-0001-5-001", "name": "洪秀全故居", "era": "清代中期", "province": "广东", "city": "花都市", "category": "modern-historic"},
    {"seq": 2, "id_num": "3-0002-5-002", "name": "林则徐墓", "era": "1826年", "province": "福建", "city": "福州市", "category": "modern-historic"},
    {"seq": 3, "id_num": "3-0003-5-003", "name": "堂子街太平天国壁画", "era": "1853-1864年", "province": "江苏", "city": "南京市", "category": "modern-historic"},
    {"seq": 4, "id_num": "3-0004-5-004", "name": "大沽口炮台", "era": "1858年", "province": "天津", "city": "塘沽区", "category": "modern-historic"},
    {"seq": 5, "id_num": "3-0005-5-005", "name": "太平天国侍王府", "era": "1861年", "province": "浙江", "city": "金华市", "category": "modern-historic"},
    {"seq": 6, "id_num": "3-0006-5-006", "name": "望海楼教堂", "era": "1869-1904年", "province": "天津", "city": "河北区", "category": "modern-historic"},
    {"seq": 7, "id_num": "3-0007-5-007", "name": "黄兴故居及墓", "era": "1874年", "province": "湖南", "city": "长沙县", "category": "modern-historic"},
    {"seq": 8, "id_num": "3-0008-5-008", "name": "绍兴鲁迅故居", "era": "1881-1898年", "province": "浙江", "city": "绍兴市", "category": "modern-historic"},
    {"seq": 9, "id_num": "3-0009-5-009", "name": "刘公岛甲午战争纪念地", "era": "1888-1895年", "province": "山东", "city": "威海市", "category": "modern-historic"},
    {"seq": 10, "id_num": "3-0010-5-010", "name": "李大钊故居", "era": "1889年", "province": "河北", "city": "乐亭县", "category": "modern-historic"},
    {"seq": 11, "id_num": "3-0011-5-011", "name": "孙中山故居", "era": "1892年", "province": "广东", "city": "中山市", "category": "modern-historic"},
    {"seq": 12, "id_num": "3-0012-5-012", "name": "朱德故居", "era": "1895-1907年", "province": "四川", "city": "仪陇县", "category": "modern-historic"},
    {"seq": 13, "id_num": "3-0013-5-013", "name": "茅盾故居", "era": "1896-1910年", "province": "浙江", "city": "桐乡县", "category": "modern-historic"},
    {"seq": 14, "id_num": "3-0014-5-014", "name": "周恩来故居", "era": "1898-1910年", "province": "江苏", "city": "淮安市", "category": "modern-historic"},
    {"seq": 15, "id_num": "3-0015-5-015", "name": "刘少奇故居", "era": "1898-1916年", "province": "湖南", "city": "宁乡县", "category": "modern-historic"},
    {"seq": 16, "id_num": "3-0016-5-016", "name": "任弼时故居", "era": "1904-1915年", "province": "湖南", "city": "汨罗市", "category": "modern-historic"},
    {"seq": 17, "id_num": "3-0017-5-017", "name": "秋瑾故居", "era": "1907年", "province": "浙江", "city": "绍兴市", "category": "modern-historic"},
    {"seq": 18, "id_num": "3-0018-5-018", "name": "云南陆军讲武堂旧址", "era": "1909-1928年", "province": "云南", "city": "昆明市", "category": "modern-historic"},
    {"seq": 19, "id_num": "3-0019-5-019", "name": "辛亥秋保路死事纪念碑", "era": "1913年", "province": "四川", "city": "成都市", "category": "modern-historic"},
    {"seq": 20, "id_num": "3-0020-5-020", "name": "国民党一大旧址", "era": "1924年", "province": "广东", "city": "广州市", "category": "modern-historic"},
    {"seq": 21, "id_num": "3-0021-5-021", "name": "黄埔军校旧址", "era": "1924-1927年", "province": "广东", "city": "广州市", "category": "modern-historic"},
    {"seq": 22, "id_num": "3-0022-5-022", "name": "中华全国总工会旧址", "era": "1925-1927年", "province": "广东", "city": "广州市", "category": "modern-historic"},
    {"seq": 23, "id_num": "3-0023-5-023", "name": "北伐汀泗桥战役遗址", "era": "1926年", "province": "湖北", "city": "咸宁市", "category": "modern-historic"},
    {"seq": 24, "id_num": "3-0024-5-024", "name": "红安七里坪革命旧址", "era": "1927-1934年", "province": "湖北", "city": "红安县", "category": "modern-historic"},
    {"seq": 25, "id_num": "3-0025-5-025", "name": "龙华革命烈士纪念地", "era": "1927-1937年", "province": "上海", "city": "徐汇区", "category": "modern-historic"},
    {"seq": 26, "id_num": "3-0026-5-026", "name": "雨花台烈士陵园", "era": "1927-1949年", "province": "江苏", "city": "南京市", "category": "modern-historic"},
    {"seq": 27, "id_num": "3-0027-5-027", "name": "平江起义旧址", "era": "1928年", "province": "湖南", "city": "平江县", "category": "modern-historic"},
    {"seq": 28, "id_num": "3-0028-5-028", "name": "中国工农红军第七军第八军军部旧址", "era": "1929-1930年", "province": "广西", "city": "百色市", "category": "modern-historic"},
    {"seq": 29, "id_num": "3-0029-5-029", "name": "长汀革命旧址", "era": "1929-1933年", "province": "福建", "city": "长汀县", "category": "modern-historic"},
    {"seq": 30, "id_num": "3-0030-5-030", "name": "湘鄂西革命根据地旧址", "era": "1930-1932年", "province": "湖北", "city": "洪湖市", "category": "modern-historic"},
    {"seq": 31, "id_num": "3-0031-5-031", "name": "宁都起义指挥部旧址", "era": "1931年", "province": "江西", "city": "宁都县", "category": "modern-historic"},
    {"seq": 32, "id_num": "3-0032-5-032", "name": "鄂豫皖革命根据地旧址", "era": "1931年", "province": "河南", "city": "新县", "category": "modern-historic"},
    {"seq": 33, "id_num": "3-0033-5-033", "name": "红四方面军总指挥部旧址", "era": "1932-1935年", "province": "四川", "city": "通江县", "category": "modern-historic"},
    {"seq": 34, "id_num": "3-0034-5-034", "name": "平顶山惨案遗址", "era": "1932年", "province": "辽宁", "city": "抚顺市", "category": "modern-historic"},
    {"seq": 35, "id_num": "3-0035-5-035", "name": "瓦窑堡革命旧址", "era": "1935年", "province": "陕西", "city": "子长县", "category": "modern-historic"},
    {"seq": 36, "id_num": "3-0036-5-036", "name": "八路军西安办事处旧址", "era": "1937-1946年", "province": "陕西", "city": "西安市", "category": "modern-historic"},
    {"seq": 37, "id_num": "3-0037-5-037", "name": "中共中央中原局旧址", "era": "1938-1939年", "province": "河南", "city": "确山县", "category": "modern-historic"},
    {"seq": 38, "id_num": "3-0038-5-038", "name": "陈嘉庚墓", "era": "1953年", "province": "福建", "city": "厦门市", "category": "modern-historic"},
    {"seq": 39, "id_num": "3-0039-5-039", "name": "冯玉祥墓", "era": "1953年", "province": "山东", "city": "泰安市", "category": "modern-historic"},
    {"seq": 40, "id_num": "3-0040-5-040", "name": "郭沫若故居", "era": "1963-1978年", "province": "北京", "city": "西城区", "category": "modern-historic"},
    {"seq": 41, "id_num": "3-0041-5-041", "name": "聂耳墓", "era": "1980年", "province": "云南", "city": "昆明市", "category": "modern-historic"},

    # === 石窟寺及石刻 (42-52) ===
    {"seq": 42, "id_num": "3-0042-4-001", "name": "孔望山摩崖造像", "era": "东汉", "province": "江苏", "city": "连云港市", "category": "stone-carvings"},
    {"seq": 43, "id_num": "3-0043-4-002", "name": "北石窟寺", "era": "北魏至宋", "province": "甘肃", "city": "西峰市", "category": "stone-carvings"},
    {"seq": 44, "id_num": "3-0044-4-003", "name": "南石窟寺", "era": "北魏至唐", "province": "甘肃", "city": "泾川县", "category": "stone-carvings"},
    {"seq": 45, "id_num": "3-0045-4-004", "name": "万佛堂石窟", "era": "北魏", "province": "辽宁", "city": "义县", "category": "stone-carvings"},
    {"seq": 46, "id_num": "3-0046-4-005", "name": "驼山石窟", "era": "北周至唐", "province": "山东", "city": "青州市", "category": "stone-carvings"},
    {"seq": 47, "id_num": "3-0047-4-006", "name": "南龛摩崖造像", "era": "隋至宋", "province": "四川", "city": "巴中县", "category": "stone-carvings"},
    {"seq": 48, "id_num": "3-0048-4-007", "name": "千佛崖造像", "era": "唐至明", "province": "山东", "city": "济南市", "category": "stone-carvings"},
    {"seq": 49, "id_num": "3-0049-4-008", "name": "大佛寺石窟", "era": "唐", "province": "陕西", "city": "彬县", "category": "stone-carvings"},
    {"seq": 50, "id_num": "3-0050-4-009", "name": "卧佛院摩崖造像", "era": "唐", "province": "四川", "city": "安岳县", "category": "stone-carvings"},
    {"seq": 51, "id_num": "3-0051-4-010", "name": "钟山石窟", "era": "北宋", "province": "陕西", "city": "子长县", "category": "stone-carvings"},
    {"seq": 52, "id_num": "3-0052-4-011", "name": "通天岩石窟", "era": "宋至明", "province": "江西", "city": "赣州市", "category": "stone-carvings"},

    # === 古建筑及历史纪念建筑物 (53-163) ===
    # 水利工程 (53-57)
    {"seq": 53, "id_num": "3-0053-3-001", "name": "安丰塘", "era": "春秋", "province": "安徽", "city": "寿县", "category": "ancient-buildings"},
    {"seq": 54, "id_num": "3-0054-3-002", "name": "灵渠", "era": "秦", "province": "广西", "city": "兴安县", "category": "ancient-buildings"},
    {"seq": 55, "id_num": "3-0055-3-003", "name": "它山堰", "era": "唐", "province": "浙江", "city": "鄞县", "category": "ancient-buildings"},
    {"seq": 56, "id_num": "3-0056-3-004", "name": "木兰陂", "era": "北宋", "province": "福建", "city": "莆田县", "category": "ancient-buildings"},
    {"seq": 57, "id_num": "3-0057-3-005", "name": "燊海井", "era": "清", "province": "四川", "city": "自贡市", "category": "ancient-buildings"},
    # 城墙 (58-62)
    {"seq": 58, "id_num": "3-0058-3-006", "name": "金山岭长城", "era": "明", "province": "河北", "city": "滦平县", "category": "ancient-buildings"},
    {"seq": 59, "id_num": "3-0059-3-007", "name": "南京城墙", "era": "明", "province": "江苏", "city": "南京市", "category": "ancient-buildings"},
    {"seq": 60, "id_num": "3-0060-3-008", "name": "平遥城墙", "era": "明", "province": "山西", "city": "平遥县", "category": "ancient-buildings"},
    {"seq": 61, "id_num": "3-0061-3-009", "name": "崇武城墙", "era": "明", "province": "福建", "city": "惠安县", "category": "ancient-buildings"},
    {"seq": 62, "id_num": "3-0062-3-010", "name": "兴城城墙", "era": "明至清", "province": "辽宁", "city": "兴城市", "category": "ancient-buildings"},
    # 古建筑 (63-99)
    {"seq": 63, "id_num": "3-0063-3-011", "name": "正阳门", "era": "明至清", "province": "北京", "city": "北京市", "category": "ancient-buildings"},
    {"seq": 64, "id_num": "3-0064-3-012", "name": "清远楼", "era": "明", "province": "河北", "city": "张家口市", "category": "ancient-buildings"},
    {"seq": 65, "id_num": "3-0065-3-013", "name": "光岳楼", "era": "明", "province": "山东", "city": "聊城市", "category": "ancient-buildings"},
    {"seq": 66, "id_num": "3-0066-3-014", "name": "岳阳楼", "era": "清", "province": "湖南", "city": "岳阳市", "category": "ancient-buildings"},
    {"seq": 67, "id_num": "3-0067-3-015", "name": "观音桥", "era": "宋", "province": "江西", "city": "星子县", "category": "ancient-buildings"},
    {"seq": 68, "id_num": "3-0068-3-016", "name": "洛阳桥", "era": "宋至明", "province": "福建", "city": "泉州市", "category": "ancient-buildings"},
    {"seq": 69, "id_num": "3-0069-3-017", "name": "广济桥", "era": "宋至明", "province": "广东", "city": "潮州市", "category": "ancient-buildings"},
    {"seq": 70, "id_num": "3-0070-3-018", "name": "古纤道", "era": "明至清", "province": "浙江", "city": "绍兴市", "category": "ancient-buildings"},
    {"seq": 71, "id_num": "3-0071-3-019", "name": "直隶总督署", "era": "清", "province": "河北", "city": "保定市", "category": "ancient-buildings"},
    {"seq": 72, "id_num": "3-0072-3-020", "name": "卓克基土司官寨", "era": "清", "province": "四川", "city": "马尔康县", "category": "ancient-buildings"},
    {"seq": 73, "id_num": "3-0073-3-021", "name": "大屯土司庄园", "era": "清至民国", "province": "贵州", "city": "毕节县", "category": "ancient-buildings"},
    {"seq": 74, "id_num": "3-0074-3-022", "name": "白鹿书院", "era": "清", "province": "江西", "city": "九江市", "category": "ancient-buildings"},
    {"seq": 75, "id_num": "3-0075-3-023", "name": "岳麓书院", "era": "清", "province": "湖南", "city": "长沙市", "category": "ancient-buildings"},
    {"seq": 76, "id_num": "3-0076-3-024", "name": "西秦会馆", "era": "清", "province": "四川", "city": "自贡市", "category": "ancient-buildings"},
    {"seq": 77, "id_num": "3-0077-3-025", "name": "聊城山陕会馆", "era": "清", "province": "山东", "city": "聊城市", "category": "ancient-buildings"},
    {"seq": 78, "id_num": "3-0078-3-026", "name": "社旗山陕会馆", "era": "清", "province": "河南", "city": "社旗县", "category": "ancient-buildings"},
    {"seq": 79, "id_num": "3-0079-3-027", "name": "胡庆余堂", "era": "清", "province": "浙江", "city": "杭州市", "category": "ancient-buildings"},
    {"seq": 80, "id_num": "3-0080-3-028", "name": "太庙", "era": "明至清", "province": "北京", "city": "北京市", "category": "ancient-buildings"},
    {"seq": 81, "id_num": "3-0081-3-029", "name": "社稷坛", "era": "明至清", "province": "北京", "city": "北京市", "category": "ancient-buildings"},
    {"seq": 82, "id_num": "3-0082-3-030", "name": "北京孔庙", "era": "元至清", "province": "北京", "city": "东城区", "category": "ancient-buildings"},
    {"seq": 83, "id_num": "3-0083-3-031", "name": "孟庙及孟府", "era": "明至清", "province": "山东", "city": "邹县", "category": "ancient-buildings"},
    {"seq": 84, "id_num": "3-0084-3-032", "name": "龙川胡氏宗祠", "era": "明至清", "province": "安徽", "city": "绩溪县", "category": "ancient-buildings"},
    {"seq": 85, "id_num": "3-0085-3-033", "name": "陈家祠堂", "era": "清", "province": "广东", "city": "广州市", "category": "ancient-buildings"},
    {"seq": 86, "id_num": "3-0086-3-034", "name": "泰宁尚书第", "era": "明", "province": "福建", "city": "泰宁县", "category": "ancient-buildings"},
    {"seq": 87, "id_num": "3-0087-3-035", "name": "丁村民宅", "era": "明至清", "province": "山西", "city": "襄汾县", "category": "ancient-buildings"},
    {"seq": 88, "id_num": "3-0088-3-036", "name": "潜口民宅", "era": "明", "province": "安徽", "city": "歙县", "category": "ancient-buildings"},
    {"seq": 89, "id_num": "3-0089-3-037", "name": "东阳卢宅", "era": "明至清", "province": "浙江", "city": "东阳县", "category": "ancient-buildings"},
    {"seq": 90, "id_num": "3-0090-3-038", "name": "祥集弄民宅", "era": "明", "province": "江西", "city": "景德镇市", "category": "ancient-buildings"},
    {"seq": 91, "id_num": "3-0091-3-039", "name": "崇礼住宅", "era": "清", "province": "北京", "city": "东城区", "category": "ancient-buildings"},
    {"seq": 92, "id_num": "3-0092-3-040", "name": "牟氏庄园", "era": "清至民国", "province": "山东", "city": "栖霞县", "category": "ancient-buildings"},
    {"seq": 93, "id_num": "3-0093-3-041", "name": "寄畅园", "era": "明至清", "province": "江苏", "city": "无锡市", "category": "ancient-buildings"},
    {"seq": 94, "id_num": "3-0094-3-042", "name": "环秀山庄", "era": "明至清", "province": "江苏", "city": "苏州市", "category": "ancient-buildings"},
    {"seq": 95, "id_num": "3-0095-3-043", "name": "十笏园", "era": "明至清", "province": "山东", "city": "潍坊市", "category": "ancient-buildings"},
    {"seq": 96, "id_num": "3-0096-3-044", "name": "罗布林卡", "era": "清", "province": "西藏", "city": "拉萨市", "category": "ancient-buildings"},
    {"seq": 97, "id_num": "3-0097-3-045", "name": "何园", "era": "清", "province": "江苏", "city": "扬州市", "category": "ancient-buildings"},
    {"seq": 98, "id_num": "3-0098-3-046", "name": "个园", "era": "清", "province": "江苏", "city": "扬州市", "category": "ancient-buildings"},
    {"seq": 99, "id_num": "3-0099-3-047", "name": "南通博物苑", "era": "清", "province": "江苏", "city": "南通市", "category": "ancient-buildings"},
    # 100: 樊敏阙及石刻 → stone-carvings (特殊分类)
    {"seq": 100, "id_num": "3-0100-3-048", "name": "樊敏阙及石刻", "era": "东汉", "province": "四川", "city": "芦山县", "category": "stone-carvings"},
    # 牌坊 (101-102)
    {"seq": 101, "id_num": "3-0101-3-049", "name": "治世玄岳牌坊", "era": "明", "province": "湖北", "city": "丹江口市", "category": "ancient-buildings"},
    {"seq": 102, "id_num": "3-0102-3-050", "name": "许国石坊", "era": "明", "province": "安徽", "city": "歙县", "category": "ancient-buildings"},
    # 古建筑 (103-159)
    {"seq": 103, "id_num": "3-0103-3-051", "name": "大士阁", "era": "明", "province": "广西", "city": "合浦县", "category": "ancient-buildings"},
    {"seq": 104, "id_num": "3-0104-3-052", "name": "增冲鼓楼", "era": "清", "province": "贵州", "city": "从江县", "category": "ancient-buildings"},
    {"seq": 105, "id_num": "3-0105-3-053", "name": "开元寺钟楼", "era": "唐至清", "province": "河北", "city": "正定县", "category": "ancient-buildings"},
    {"seq": 106, "id_num": "3-0106-3-054", "name": "法兴寺", "era": "唐", "province": "山西", "city": "长子县", "category": "ancient-buildings"},
    {"seq": 107, "id_num": "3-0107-3-055", "name": "天台庵", "era": "唐", "province": "山西", "city": "平顺县", "category": "ancient-buildings"},
    {"seq": 108, "id_num": "3-0108-3-056", "name": "风穴寺及塔林", "era": "唐至清", "province": "河南", "city": "临汝县", "category": "ancient-buildings"},
    {"seq": 109, "id_num": "3-0109-3-057", "name": "昭仁寺大殿", "era": "唐", "province": "陕西", "city": "长武县", "category": "ancient-buildings"},
    {"seq": 110, "id_num": "3-0110-3-058", "name": "青莲寺", "era": "唐至清", "province": "山西", "city": "晋城市", "category": "ancient-buildings"},
    {"seq": 111, "id_num": "3-0111-3-059", "name": "镇国寺", "era": "五代至清", "province": "山西", "city": "平遥县", "category": "ancient-buildings"},
    {"seq": 112, "id_num": "3-0112-3-060", "name": "大云院", "era": "五代至清", "province": "山西", "city": "平顺县", "category": "ancient-buildings"},
    {"seq": 113, "id_num": "3-0113-3-061", "name": "玉皇庙", "era": "宋至清", "province": "山西", "city": "晋城市", "category": "ancient-buildings"},
    {"seq": 114, "id_num": "3-0114-3-062", "name": "大庙飞来殿", "era": "宋至元", "province": "四川", "city": "峨眉县", "category": "ancient-buildings"},
    {"seq": 115, "id_num": "3-0115-3-063", "name": "云岩寺", "era": "宋至清", "province": "四川", "city": "江油县", "category": "ancient-buildings"},
    {"seq": 116, "id_num": "3-0116-3-064", "name": "天宁寺大殿", "era": "宋至元", "province": "浙江", "city": "金华市", "category": "ancient-buildings"},
    {"seq": 117, "id_num": "3-0117-3-065", "name": "崇福寺", "era": "金", "province": "山西", "city": "朔县", "category": "ancient-buildings"},
    {"seq": 118, "id_num": "3-0118-3-066", "name": "夏鲁寺", "era": "元至清", "province": "西藏", "city": "日喀则市", "category": "ancient-buildings"},
    {"seq": 119, "id_num": "3-0119-3-067", "name": "法海寺", "era": "明", "province": "北京", "city": "石景山区", "category": "ancient-buildings"},
    {"seq": 120, "id_num": "3-0120-3-068", "name": "双林寺", "era": "明", "province": "山西", "city": "平遥县", "category": "ancient-buildings"},
    {"seq": 121, "id_num": "3-0121-3-069", "name": "殊像寺", "era": "清", "province": "河北", "city": "承德市", "category": "ancient-buildings"},
    {"seq": 122, "id_num": "3-0122-3-070", "name": "安远庙", "era": "清", "province": "河北", "city": "承德市", "category": "ancient-buildings"},
    {"seq": 123, "id_num": "3-0123-3-071", "name": "广允缅寺", "era": "清", "province": "云南", "city": "沧源佤族自治县", "category": "ancient-buildings"},
    {"seq": 124, "id_num": "3-0124-3-072", "name": "景真八角亭", "era": "清", "province": "云南", "city": "勐海县", "category": "ancient-buildings"},
    {"seq": 125, "id_num": "3-0125-3-073", "name": "岱庙", "era": "宋至清", "province": "山东", "city": "泰安市", "category": "ancient-buildings"},
    {"seq": 126, "id_num": "3-0126-3-074", "name": "西岳庙", "era": "明至清", "province": "陕西", "city": "华阴县", "category": "ancient-buildings"},
    {"seq": 127, "id_num": "3-0127-3-075", "name": "北镇庙", "era": "明至清", "province": "辽宁", "city": "北镇县", "category": "ancient-buildings"},
    {"seq": 128, "id_num": "3-0128-3-076", "name": "玄贞观", "era": "明", "province": "辽宁", "city": "盖县", "category": "ancient-buildings"},
    {"seq": 129, "id_num": "3-0129-3-077", "name": "万荣东岳庙", "era": "元至清", "province": "山西", "city": "万荣县", "category": "ancient-buildings"},
    {"seq": 130, "id_num": "3-0130-3-078", "name": "解州关帝庙", "era": "清", "province": "山西", "city": "运城市", "category": "ancient-buildings"},
    {"seq": 131, "id_num": "3-0131-3-079", "name": "花戏楼", "era": "清", "province": "安徽", "city": "亳州市", "category": "ancient-buildings"},
    {"seq": 132, "id_num": "3-0132-3-080", "name": "青龙洞", "era": "清", "province": "贵州", "city": "镇远县", "category": "ancient-buildings"},
    {"seq": 133, "id_num": "3-0133-3-081", "name": "泉州天后宫", "era": "清", "province": "福建", "city": "泉州市", "category": "ancient-buildings"},
    {"seq": 134, "id_num": "3-0134-3-082", "name": "牛街礼拜寺", "era": "明至清", "province": "北京", "city": "宣武区", "category": "ancient-buildings"},
    {"seq": 135, "id_num": "3-0135-3-083", "name": "西安清真寺", "era": "明至清", "province": "陕西", "city": "西安市", "category": "ancient-buildings"},
    {"seq": 136, "id_num": "3-0136-3-084", "name": "同心清真大寺", "era": "清", "province": "宁夏", "city": "同心县", "category": "ancient-buildings"},
    {"seq": 137, "id_num": "3-0137-3-085", "name": "净藏禅师塔", "era": "唐", "province": "河南", "city": "登封县", "category": "ancient-buildings"},
    {"seq": 138, "id_num": "3-0138-3-086", "name": "云龙寺塔", "era": "唐", "province": "广东", "city": "仁化县", "category": "ancient-buildings"},
    {"seq": 139, "id_num": "3-0139-3-087", "name": "凌霄塔", "era": "唐至宋", "province": "河北", "city": "正定县", "category": "ancient-buildings"},
    {"seq": 140, "id_num": "3-0140-3-088", "name": "朝阳北塔", "era": "唐至辽", "province": "辽宁", "city": "朝阳市", "category": "ancient-buildings"},
    {"seq": 141, "id_num": "3-0141-3-089", "name": "灵光塔", "era": "渤海", "province": "吉林", "city": "长白朝鲜族自治县", "category": "ancient-buildings"},
    {"seq": 142, "id_num": "3-0142-3-090", "name": "闸口白塔", "era": "五代", "province": "浙江", "city": "杭州市", "category": "ancient-buildings"},
    {"seq": 143, "id_num": "3-0143-3-091", "name": "栖霞寺舍利塔", "era": "五代", "province": "江苏", "city": "南京市", "category": "ancient-buildings"},
    {"seq": 144, "id_num": "3-0144-3-092", "name": "三影塔", "era": "北宋", "province": "广东", "city": "南雄县", "category": "ancient-buildings"},
    {"seq": 145, "id_num": "3-0145-3-093", "name": "广教寺双塔", "era": "北宋", "province": "安徽", "city": "宣州市", "category": "ancient-buildings"},
    {"seq": 146, "id_num": "3-0146-3-094", "name": "崇觉寺铁塔", "era": "北宋", "province": "山东", "city": "济宁市", "category": "ancient-buildings"},
    {"seq": 147, "id_num": "3-0147-3-095", "name": "瑞光塔", "era": "北宋", "province": "江苏", "city": "苏州市", "category": "ancient-buildings"},
    {"seq": 148, "id_num": "3-0148-3-096", "name": "飞英塔", "era": "南宋", "province": "浙江", "city": "湖州市", "category": "ancient-buildings"},
    {"seq": 149, "id_num": "3-0149-3-097", "name": "释迦文佛塔", "era": "南宋", "province": "福建", "city": "莆田县", "category": "ancient-buildings"},
    {"seq": 150, "id_num": "3-0150-3-098", "name": "天宁寺塔", "era": "辽", "province": "北京", "city": "宣武区", "category": "ancient-buildings"},
    {"seq": 151, "id_num": "3-0151-3-099", "name": "崇兴寺双塔", "era": "辽", "province": "辽宁", "city": "北镇县", "category": "ancient-buildings"},
    {"seq": 152, "id_num": "3-0152-3-100", "name": "辽阳白塔", "era": "辽至金", "province": "辽宁", "city": "辽阳市", "category": "ancient-buildings"},
    {"seq": 153, "id_num": "3-0153-3-101", "name": "银山塔林", "era": "金至元", "province": "北京", "city": "昌平县", "category": "ancient-buildings"},
    {"seq": 154, "id_num": "3-0154-3-102", "name": "拜寺口双塔", "era": "西夏", "province": "宁夏", "city": "贺兰县", "category": "ancient-buildings"},
    {"seq": 155, "id_num": "3-0155-3-103", "name": "一百零八塔", "era": "元", "province": "宁夏", "city": "青铜峡市", "category": "ancient-buildings"},
    {"seq": 156, "id_num": "3-0156-3-104", "name": "广德寺多宝塔", "era": "明", "province": "湖北", "city": "襄樊市", "category": "ancient-buildings"},
    {"seq": 157, "id_num": "3-0157-3-105", "name": "曼飞龙塔", "era": "清", "province": "云南", "city": "景洪县", "category": "ancient-buildings"},
    {"seq": 158, "id_num": "3-0158-3-106", "name": "金刚座舍利宝塔", "era": "清", "province": "内蒙古", "city": "呼和浩特市", "category": "ancient-buildings"},
    {"seq": 159, "id_num": "3-0159-3-107", "name": "苏公塔", "era": "清", "province": "新疆", "city": "吐鲁番市", "category": "ancient-buildings"},
    # 旧址 → modern-historic (160-163)
    {"seq": 160, "id_num": "3-0160-3-108", "name": "旅顺监狱旧址", "era": "1898-1945年", "province": "辽宁", "city": "大连市", "category": "modern-historic"},
    {"seq": 161, "id_num": "3-0161-3-109", "name": "息烽集中营旧址", "era": "1937-1946年", "province": "贵州", "city": "息烽县", "category": "modern-historic"},
    {"seq": 162, "id_num": "3-0162-3-110", "name": "上饶集中营旧址", "era": "1941-1942年", "province": "江西", "city": "上饶县", "category": "modern-historic"},
    {"seq": 163, "id_num": "3-0163-3-111", "name": "中美合作所集中营旧址", "era": "1943-1949年", "province": "重庆", "city": "重庆市", "category": "modern-historic"},

    # === 石刻及其他 (164-180) ===
    {"seq": 164, "id_num": "3-0164-4-001", "name": "将军崖岩画", "era": "新石器时代", "province": "江苏", "city": "连云港市", "category": "stone-carvings"},
    {"seq": 165, "id_num": "3-0165-4-002", "name": "花山岩画", "era": "战国至东汉", "province": "广西", "city": "宁明县", "category": "stone-carvings"},
    {"seq": 166, "id_num": "3-0166-4-003", "name": "亚沟石刻", "era": "金", "province": "黑龙江", "city": "阿城市", "category": "stone-carvings"},
    {"seq": 167, "id_num": "3-0167-4-004", "name": "南京南朝陵墓石刻", "era": "南朝", "province": "江苏", "city": "南京市", "category": "stone-carvings"},
    {"seq": 168, "id_num": "3-0168-4-005", "name": "丹阳南朝陵墓石刻", "era": "南朝", "province": "江苏", "city": "丹阳市", "category": "stone-carvings"},
    {"seq": 169, "id_num": "3-0169-4-006", "name": "老君岩造像", "era": "宋", "province": "福建", "city": "泉州市", "category": "stone-carvings"},
    {"seq": 170, "id_num": "3-0170-4-007", "name": "云峰山天柱山摩崖石刻", "era": "北魏", "province": "山东", "city": "掖县", "category": "stone-carvings"},
    {"seq": 171, "id_num": "3-0171-4-008", "name": "铁山岗山摩崖石刻", "era": "北周", "province": "山东", "city": "邹县", "category": "stone-carvings"},
    {"seq": 172, "id_num": "3-0172-4-009", "name": "白鹤梁题刻", "era": "唐至清", "province": "重庆", "city": "涪陵区", "category": "stone-carvings"},
    {"seq": 173, "id_num": "3-0173-4-010", "name": "浯溪摩崖石刻", "era": "唐至清", "province": "湖南", "city": "祁阳县", "category": "stone-carvings"},
    {"seq": 174, "id_num": "3-0174-4-011", "name": "袁滋题记摩崖石刻", "era": "唐", "province": "云南", "city": "盐津县", "category": "stone-carvings"},
    {"seq": 175, "id_num": "3-0175-4-012", "name": "怡亭铭摩崖石刻", "era": "唐", "province": "湖北", "city": "鄂州市", "category": "stone-carvings"},
    {"seq": 176, "id_num": "3-0176-4-013", "name": "九日山摩崖石刻", "era": "宋", "province": "福建", "city": "南安县", "category": "stone-carvings"},
    {"seq": 177, "id_num": "3-0177-4-014", "name": "焦山碑林", "era": "南朝至清", "province": "江苏", "city": "镇江市", "category": "stone-carvings"},
    {"seq": 178, "id_num": "3-0178-4-015", "name": "大金得胜陀颂碑", "era": "金", "province": "吉林", "city": "扶余市", "category": "stone-carvings"},
    {"seq": 179, "id_num": "3-0179-4-016", "name": "松江唐经幢", "era": "唐", "province": "上海", "city": "松江县", "category": "stone-carvings"},
    {"seq": 180, "id_num": "3-0180-4-017", "name": "南诏铁柱", "era": "南诏", "province": "云南", "city": "弥渡县", "category": "others"},

    # === 古遗址 (181-229) ===
    {"seq": 181, "id_num": "3-0181-1-001", "name": "腊玛古猿化石地点", "era": "远古", "province": "云南", "city": "禄丰县", "category": "archaeological-sites"},
    {"seq": 182, "id_num": "3-0182-1-002", "name": "西侯度遗址", "era": "旧石器时代", "province": "山西", "city": "芮城县", "category": "archaeological-sites"},
    {"seq": 183, "id_num": "3-0183-1-003", "name": "金牛山遗址", "era": "旧石器时代", "province": "辽宁", "city": "营口县", "category": "archaeological-sites"},
    {"seq": 184, "id_num": "3-0184-1-004", "name": "和县猿人遗址", "era": "旧石器时代", "province": "安徽", "city": "和县", "category": "archaeological-sites"},
    {"seq": 185, "id_num": "3-0185-1-005", "name": "水洞沟遗址", "era": "旧石器时代", "province": "宁夏", "city": "灵武县", "category": "archaeological-sites"},
    {"seq": 186, "id_num": "3-0186-1-006", "name": "穿洞遗址", "era": "旧石器时代", "province": "贵州", "city": "普定县", "category": "archaeological-sites"},
    {"seq": 187, "id_num": "3-0187-1-007", "name": "大窑遗址", "era": "旧石器时代", "province": "内蒙古", "city": "呼和浩特市", "category": "archaeological-sites"},
    {"seq": 188, "id_num": "3-0188-1-008", "name": "磁山遗址", "era": "新石器时代", "province": "河北", "city": "武安县", "category": "archaeological-sites"},
    {"seq": 189, "id_num": "3-0189-1-009", "name": "大地湾遗址", "era": "新石器时代", "province": "甘肃", "city": "秦安县", "category": "archaeological-sites"},
    {"seq": 190, "id_num": "3-0190-1-010", "name": "马家窑遗址", "era": "新石器时代", "province": "甘肃", "city": "临洮县", "category": "archaeological-sites"},
    {"seq": 191, "id_num": "3-0191-1-011", "name": "马厂塬遗址", "era": "新石器时代", "province": "青海", "city": "民和县", "category": "archaeological-sites"},
    {"seq": 192, "id_num": "3-0192-1-012", "name": "陶寺遗址", "era": "新石器时代", "province": "山西", "city": "襄汾县", "category": "archaeological-sites"},
    {"seq": 193, "id_num": "3-0193-1-013", "name": "平粮台古城遗址", "era": "新石器时代", "province": "河南", "city": "淮阳县", "category": "archaeological-sites"},
    {"seq": 194, "id_num": "3-0194-1-014", "name": "屈家岭遗址", "era": "新石器时代", "province": "湖北", "city": "京山县", "category": "archaeological-sites"},
    {"seq": 195, "id_num": "3-0195-1-015", "name": "牛河梁遗址", "era": "新石器时代", "province": "辽宁", "city": "凌源县", "category": "archaeological-sites"},
    {"seq": 196, "id_num": "3-0196-1-016", "name": "昂昂溪遗址", "era": "新石器时代", "province": "黑龙江", "city": "齐齐哈尔市", "category": "archaeological-sites"},
    {"seq": 197, "id_num": "3-0197-1-017", "name": "二里头遗址", "era": "夏商", "province": "河南", "city": "偃师县", "category": "archaeological-sites"},
    {"seq": 198, "id_num": "3-0198-1-018", "name": "尸乡沟商城遗址", "era": "商", "province": "河南", "city": "偃师县", "category": "archaeological-sites"},
    {"seq": 199, "id_num": "3-0199-1-019", "name": "盘龙城遗址", "era": "商", "province": "湖北", "city": "黄陂县", "category": "archaeological-sites"},
    {"seq": 200, "id_num": "3-0200-1-020", "name": "三星堆遗址", "era": "商周", "province": "四川", "city": "广汉县", "category": "archaeological-sites"},
    {"seq": 201, "id_num": "3-0201-1-021", "name": "琉璃河遗址", "era": "西周", "province": "北京", "city": "房山区", "category": "archaeological-sites"},
    {"seq": 202, "id_num": "3-0202-1-022", "name": "薛城遗址", "era": "东周", "province": "山东", "city": "滕县", "category": "archaeological-sites"},
    {"seq": 203, "id_num": "3-0203-1-023", "name": "淹城遗址", "era": "东周", "province": "江苏", "city": "武进县", "category": "archaeological-sites"},
    {"seq": 204, "id_num": "3-0204-1-024", "name": "秦雍城遗址", "era": "东周", "province": "陕西", "city": "凤翔县", "category": "archaeological-sites"},
    {"seq": 205, "id_num": "3-0205-1-025", "name": "禹王城遗址", "era": "东周至汉", "province": "山西", "city": "夏县", "category": "archaeological-sites"},
    {"seq": 206, "id_num": "3-0206-1-026", "name": "中山古城遗址", "era": "战国", "province": "河北", "city": "平山县", "category": "archaeological-sites"},
    {"seq": 207, "id_num": "3-0207-1-027", "name": "秦咸阳城遗址", "era": "战国至秦", "province": "陕西", "city": "咸阳市", "category": "archaeological-sites"},
    {"seq": 208, "id_num": "3-0208-1-028", "name": "姜女石遗址", "era": "秦汉", "province": "辽宁", "city": "绥中县", "category": "archaeological-sites"},
    {"seq": 209, "id_num": "3-0209-1-029", "name": "居延遗址", "era": "汉", "province": "内蒙古", "city": "额济纳旗", "category": "archaeological-sites"},
    {"seq": 210, "id_num": "3-0210-1-030", "name": "玉门关及长城烽燧遗址", "era": "汉", "province": "甘肃", "city": "敦煌市", "category": "archaeological-sites"},
    {"seq": 211, "id_num": "3-0211-1-031", "name": "楼兰故城遗址", "era": "汉至晋", "province": "新疆", "city": "若羌县", "category": "archaeological-sites"},
    {"seq": 212, "id_num": "3-0212-1-032", "name": "西海郡故城遗址", "era": "汉至南北朝", "province": "青海", "city": "海晏县", "category": "archaeological-sites"},
    {"seq": 213, "id_num": "3-0213-1-033", "name": "邺城遗址", "era": "曹魏至北齐", "province": "河北", "city": "临漳县", "category": "archaeological-sites"},
    {"seq": 214, "id_num": "3-0214-1-034", "name": "嘎仙洞遗址", "era": "北魏", "province": "内蒙古", "city": "鄂伦春自治旗", "category": "archaeological-sites"},
    {"seq": 215, "id_num": "3-0215-1-035", "name": "平城遗址", "era": "北魏", "province": "山西", "city": "大同市", "category": "archaeological-sites"},
    {"seq": 216, "id_num": "3-0216-1-036", "name": "隋唐洛阳城遗址", "era": "隋唐", "province": "河南", "city": "洛阳市", "category": "archaeological-sites"},
    {"seq": 217, "id_num": "3-0217-1-037", "name": "北庭故城遗址", "era": "唐", "province": "新疆", "city": "吉木萨尔县", "category": "archaeological-sites"},
    {"seq": 218, "id_num": "3-0218-1-038", "name": "北宋东京城遗址", "era": "北宋", "province": "河南", "city": "开封市", "category": "archaeological-sites"},
    {"seq": 219, "id_num": "3-0219-1-039", "name": "蒲与路故城遗址", "era": "金", "province": "黑龙江", "city": "克东县", "category": "archaeological-sites"},
    {"seq": 220, "id_num": "3-0220-1-040", "name": "元上都遗址", "era": "元", "province": "内蒙古", "city": "正蓝旗", "category": "archaeological-sites"},
    {"seq": 221, "id_num": "3-0221-1-041", "name": "圆明园遗址", "era": "清", "province": "北京", "city": "海淀区", "category": "archaeological-sites"},
    {"seq": 222, "id_num": "3-0222-1-042", "name": "上林湖越窑遗址", "era": "东汉至宋", "province": "浙江", "city": "慈溪县", "category": "archaeological-sites"},
    {"seq": 223, "id_num": "3-0223-1-043", "name": "什邡堂邛窑遗址", "era": "隋至宋", "province": "四川", "city": "邛崃县", "category": "archaeological-sites"},
    {"seq": 224, "id_num": "3-0224-1-044", "name": "长沙铜官窑遗址", "era": "唐至宋", "province": "湖南", "city": "望城县", "category": "archaeological-sites"},
    {"seq": 225, "id_num": "3-0225-1-045", "name": "涧磁村定窑遗址", "era": "唐至元", "province": "河北", "city": "曲阳县", "category": "archaeological-sites"},
    {"seq": 226, "id_num": "3-0226-1-046", "name": "黄堡镇耀州窑遗址", "era": "唐至元", "province": "陕西", "city": "铜川市", "category": "archaeological-sites"},
    {"seq": 227, "id_num": "3-0227-1-047", "name": "钧台钧窑遗址", "era": "宋", "province": "河南", "city": "禹县", "category": "archaeological-sites"},
    {"seq": 228, "id_num": "3-0228-1-048", "name": "大窑龙泉窑遗址", "era": "宋至明", "province": "浙江", "city": "龙泉县", "category": "archaeological-sites"},
    {"seq": 229, "id_num": "3-0229-1-049", "name": "屈斗宫德化窑遗址", "era": "宋至明", "province": "福建", "city": "德化县", "category": "archaeological-sites"},

    # === 古墓葬 (230-258) ===
    {"seq": 230, "id_num": "3-0230-2-001", "name": "八岭山古墓群", "era": "东周至明", "province": "湖北", "city": "江陵县", "category": "ancient-tombs"},
    {"seq": 231, "id_num": "3-0231-2-002", "name": "擂鼓墩古墓群", "era": "战国", "province": "湖北", "city": "随州市", "category": "ancient-tombs"},
    {"seq": 232, "id_num": "3-0232-2-003", "name": "田齐王陵", "era": "战国", "province": "山东", "city": "淄博市", "category": "ancient-tombs"},
    {"seq": 233, "id_num": "3-0233-2-004", "name": "长陵", "era": "西汉", "province": "陕西", "city": "咸阳市", "category": "ancient-tombs"},
    {"seq": 234, "id_num": "3-0234-2-005", "name": "杜陵", "era": "西汉", "province": "陕西", "city": "长安县", "category": "ancient-tombs"},
    {"seq": 235, "id_num": "3-0235-2-006", "name": "中山靖王墓", "era": "西汉", "province": "河北", "city": "满城县", "category": "ancient-tombs"},
    {"seq": 236, "id_num": "3-0236-2-007", "name": "广武汉墓群", "era": "汉", "province": "山西", "city": "山阴县", "category": "ancient-tombs"},
    {"seq": 237, "id_num": "3-0237-2-008", "name": "张衡墓", "era": "东汉", "province": "河南", "city": "南阳县", "category": "ancient-tombs"},
    {"seq": 238, "id_num": "3-0238-2-009", "name": "麻浩崖墓", "era": "东汉至南北朝", "province": "四川", "city": "乐山市", "category": "ancient-tombs"},
    {"seq": 239, "id_num": "3-0239-2-010", "name": "打虎亭汉墓", "era": "东汉", "province": "河南", "city": "密县", "category": "ancient-tombs"},
    {"seq": 240, "id_num": "3-0240-2-011", "name": "张仲景墓及祠", "era": "东汉", "province": "河南", "city": "南阳市", "category": "ancient-tombs"},
    {"seq": 241, "id_num": "3-0241-2-012", "name": "阿斯塔那古墓群", "era": "晋至唐", "province": "新疆", "city": "吐鲁番市", "category": "ancient-tombs"},
    {"seq": 242, "id_num": "3-0242-2-013", "name": "磁县北朝墓群", "era": "北朝", "province": "河北", "city": "磁县", "category": "ancient-tombs"},
    {"seq": 243, "id_num": "3-0243-2-014", "name": "桥陵", "era": "唐", "province": "陕西", "city": "蒲城县", "category": "ancient-tombs"},
    {"seq": 244, "id_num": "3-0244-2-015", "name": "龙头山古墓群", "era": "渤海", "province": "吉林", "city": "和龙县", "category": "ancient-tombs"},
    {"seq": 245, "id_num": "3-0245-2-016", "name": "南唐二陵", "era": "五代", "province": "江苏", "city": "江宁县", "category": "ancient-tombs"},
    {"seq": 246, "id_num": "3-0246-2-017", "name": "司马光墓", "era": "北宋", "province": "山西", "city": "夏县", "category": "ancient-tombs"},
    {"seq": 247, "id_num": "3-0247-2-018", "name": "辽陵及奉陵邑", "era": "辽", "province": "内蒙古", "city": "巴林左旗", "category": "ancient-tombs"},
    {"seq": 248, "id_num": "3-0248-2-019", "name": "西夏陵", "era": "西夏", "province": "宁夏", "city": "银川市", "category": "ancient-tombs"},
    {"seq": 249, "id_num": "3-0249-2-020", "name": "僰人悬棺葬", "era": "宋至清", "province": "四川", "city": "珙县", "category": "ancient-tombs"},
    {"seq": 250, "id_num": "3-0250-2-021", "name": "伊斯兰教圣墓", "era": "元", "province": "福建", "city": "泉州市", "category": "ancient-tombs"},
    {"seq": 251, "id_num": "3-0251-2-022", "name": "奢香墓", "era": "明", "province": "贵州", "city": "大方县", "category": "ancient-tombs"},
    {"seq": 252, "id_num": "3-0252-2-023", "name": "苏禄王墓", "era": "明", "province": "山东", "city": "德州市", "category": "ancient-tombs"},
    {"seq": 253, "id_num": "3-0253-2-024", "name": "显陵", "era": "明", "province": "湖北", "city": "钟祥县", "category": "ancient-tombs"},
    {"seq": 254, "id_num": "3-0254-2-025", "name": "徐光启墓", "era": "明", "province": "上海", "city": "徐汇区", "category": "ancient-tombs"},
    {"seq": 255, "id_num": "3-0255-2-026", "name": "李自成墓", "era": "清", "province": "湖北", "city": "通山县", "category": "ancient-tombs"},
    {"seq": 256, "id_num": "3-0256-2-027", "name": "永陵", "era": "清", "province": "辽宁", "city": "新宾满族自治县", "category": "ancient-tombs"},
    {"seq": 257, "id_num": "3-0257-2-028", "name": "福陵", "era": "清", "province": "辽宁", "city": "沈阳市", "category": "ancient-tombs"},
    {"seq": 258, "id_num": "3-0258-2-029", "name": "阿巴和加麻札", "era": "清", "province": "新疆", "city": "喀什市", "category": "ancient-tombs"},
]

def build_item(raw):
    code = PROVINCE_CODE[raw["province"]]
    return {
        "id": raw["id_num"],
        "name": raw["name"],
        "level": "national",
        "batch": 3,
        "category": raw["category"],
        "province": PROVINCE_FULL[code],
        "city": raw["city"],
        "district": "",
        "address": "",
        "era": raw["era"],
        "description": "",
        "historical_value": "",
        "sources": ["维基百科-第三批全国重点文物保护单位"],
        "last_updated": "2026-03-06",
        "data_quality": "basic",
        "contributors": ["iBo"]
    }

def main():
    by_province = {}
    for raw in BATCH3:
        code = PROVINCE_CODE[raw["province"]]
        by_province.setdefault(code, []).append(build_item(raw))

    out_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "national-level")
    os.makedirs(out_dir, exist_ok=True)

    total_new = 0
    for code, items in sorted(by_province.items()):
        path = os.path.join(out_dir, f"{code}.json")
        existing = {}
        if os.path.exists(path):
            with open(path) as f:
                for item in json.load(f):
                    existing[item["id"]] = item
        for item in items:
            if item["id"] not in existing:
                existing[item["id"]] = item
                total_new += 1
            else:
                if "batch" not in existing[item["id"]]:
                    existing[item["id"]]["batch"] = 3
        merged = sorted(existing.values(), key=lambda x: x["id"])
        with open(path, "w", encoding="utf-8") as f:
            json.dump(merged, f, ensure_ascii=False, indent=2)
        print(f"  {PROVINCE_FULL[code]} ({code}.json): {len(merged)} items total")

    print(f"\n✅ 第三批 258 项录入完成 (新增 {total_new} 项)")

if __name__ == "__main__":
    main()
